(
 (plt:framework-pref:framework:white-on-black? #f)
 (plt:framework-pref:framework:exit-when-no-frames #t)
 (plt:framework-pref:framework:standard-style-list:font-size #2(#hash((((1920 1080)) . 12)) 12))
 (plt:framework-pref:framework:color-scheme-light classic)
 (plt:framework-pref:framework:delegatee-overview-color (173 216 230 1.0))
 (|plt:DrRacket 9.1-splash-max-width| 1005)
 (plt:framework-pref:plt:debug-tool:stack/variable-area 9/10)
 (plt:framework-pref:drracket:window-size #hash((#f . (#t 600 650)) (((0 0 1920 1080)) . (#t 600 650))))
 (plt:framework-pref:drracket:recent-language-names (("Determine language from source" #6(#t print mixed-fraction-e #f #t debug) (default) #0() #f #t #t ((test) (main)) #t)))
 (plt:framework-pref:drracket:language-settings ((-32768) (#6(#t print mixed-fraction-e #f #t debug) (default) #0() #f #t #t ((test) (main)) #t)))
 (plt:framework-pref:drracket:most-recent-lang-line "#lang racket\n")
 (plt:framework-pref:drracket:unit-window-size-percentage 1/2)
 (|plt:framework-pref:MacroStepper:Frame:Width| 1920)
 (|plt:framework-pref:MacroStepper:Frame:Height| 1028)
 (plt:framework-pref:framework:verify-exit #t)
 (plt:framework-pref:framework:last-opened-files ())
 (plt:framework-pref:drracket:recently-closed-tabs ())
 (plt:framework-pref:drracket:console-previous-exprs (("\"Hello, World!\"")))
 (readline-input-history
  (
   #"(exit)"
   #"exit"
   #"q"
   #"(enter! \"sort.rkt\")"
   #"(!enter \"sort.rkt\")"
   #"(!enter sort.rkt)"
   #"(when x 'true)"
   #"(define x (> 2 1 ))"
   #"(when x 'true)"
   #"(define x (> 0 1 ))"
   #"(when (> 2 1) 'true)"
   #"(when (> 0 1) 'true)"
   #"(when > 0 1 'true 'false 'true)"
   #"(when > 0 1 'true 'false)"
   #"(when > 0 1 'true)"
   #"(> 0 1)"
   #"is-it-even"
   #"(define is-it-even #f)"
   #"(enter! \"linked_list.rkt\")"
   #"(car (cdr my-list))"
   #"(cdr my-list)"
   #"cdr my-list"
   #"(enter! \"linked_list.rkt\")"
   #"(enter! linked_list.rkt)"
   #"q"
   #"load linked_list.rkt"
   #"load linked_list"
   #"ls"
   #"(odd-even 3)"
   #"(odd-even 2)"
   #"(if 0 \"zero\" \"not\")"
   #"(define (odd-even n) (if (remainder n 2) \"even\" \"odd\"))"
   #"(remainder 3 3\n           )"
   #"(remainder 3 2\n           )"
   #"(remainder 2 3)"
   #"(+ 2 3 )"
   #"(mod 2 3)"
   #"(2 mod 3)"
   #"2 module 3"
   #"2 mod 3"
   #"(odd-even 10232211123122\n          )"
   #"(odd-even 10232211123121)"
   #"(odd-even 3)"
   #"(odd-even 2)"
   #"(odd-even 1)"
   #"1 odd-even"
   #"odd-even 1"
   #"(define (odd-even n) (if (odd? n) \"odd\" \"even\"))"
   #"(if (odd? 5) \"odd\" \"even\")"
   #"(if odd? 5 \"odd\" \"even\"\n    )"
   #"(if false\n    \"except #f counts as #t\"\n    \"aw-heck\"\n    )"
   #"(if empty\n    \"except #f counts as #t\"\n    \"aw-heck\"\n    )"
   #"(if '(1)\n    \"except #f counts as #t\"\n    \"aw-heck\"\n    )"
   #"jkjk"
   #"(third l)"
   #"(second l)"
   #"(first l)"
   #"l"
   #"(rest (first ll))"
   #"ll"
   #"(define ll '((1 2 3) \n             (4 5 6)))"
   #"(rest (first ll))"
   #"(first ll)"
   #"(rest ll)"
   #"(rest (first ll))"
   #"(first ll)"
   #"ll"
   #"(define ll '('(1 2 3) '(4 5 6)))"
   #"(tail l)"
   #"(first (rest l))"
   #"l"
   #"(rest l)"
   #"l"
   #"(first l)"
   #"first l"
   #"l"
   #"(define l '(a b c d))"
   #"(cons 'chicken '())"
   #"(cons 'chicken empty)"
   #"'()"
   #"()"
   #"(list)"
   #"(cdr cell)"
   #"(car cell)"
   #"(define cell (cons 'a 'b))"
   #"(cons 1 2 )"
   #"(list 1 2 3 )"
   #"(cons 1 (cons 2 (cons 3 empty)))"
   #"(string-append \"tutti\" \" \" \"frutti\")"
   #"(/ 4.0 6)"
   #"(/ 4 6)"
   #"(expt 53 53)"
   #"(expt 2 4)"
   #"(symbol=? 'gand 'gand)"
   #"(symbol=? 'gand 'GAND)"
   #"(exit)"
   #"(bigger)"
   #"(smaller)"
   #"(bigger)"
   #"(smaller)"
   #"smaller"
   #"(start 1 100\n       )"
   #"(smaller)"
   #"smaller"
   #"(start 1 30)"
   #"(enter! \"guess_thy_number.rkt\")"
   #"(smaller)"
   #"(bigger)"
   #"(smaller)"
   #"(guess)"
   #"(enter! \"guess_thy_number.rkt\")"
   #"(exit)"
   #"(east)"
   #"(enter! \"guess_thy_number.rkt\")"
   #"(east)"
   #"(west)"
   #"(guess)"
   #"(enter! \"guess_thy_number.rkt\")"
   #"!ls"
   #"(exit)"
   #"(west)"
   #"(reload)"
   #"reload"
   #"(west)"
   #"(guess)"
   #"(exit)"
   #"q"
   #"(guess)"
   #"(exit)"
   #"exit"
   #"(guess)"
   #"(enter! \"guess_thy_number.rkt\")"
   #"(enter! \"guess_thy_number\")"
   #"(exit)"
   #"q"
   #"(guess)"
   #"(require \"guess_thy_number.rkt\")"
   #"(guess)"
   #"(exit)"
   #"(guess)"
   #"(exit)"
   #"(guess)"
   #"(exit)"
   #"quit"
   #"q"
   #"quit"
   #"+ 2 3"
   #"3"
   #"2"
   #"\"Hello, World\""
   #"'(hello world)"
   #"'(sqrt ( + (sqr 3) (sqr 4) ) )"
   #"(sqrt -9)"
   #"sqrt -9"
   #"define a = '(1 2 3 4 5)"
   #"'(1 2 3 4 5)"
   #"(sqrt ( + (sqr 3) (sqr 4)))"
   #"(exit)"
   #"quit"
   #"exit"
   #"(exit)"
   #",bt"
   #"break"
   #"q"
   #"exit"
   #"quit"
   #"\"Hello, World\""
  ))
)
