;==========================================================
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;==========================================================

[colors]
background = #121212
background-alt = #373B41
foreground = #F2F0EF
primary = #88b090
secondary = #ccdc90
alert = #e89393
disabled = #707880

[bar/main]
width = 100%
height = 20pt
radius = 0
fixed-center = true
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = "Pango Monospace:size=10;2"
font-1 = "FontAwesome:size=10;2"
font-2 = "Noto Sans Symbols2:size=10;2"
font-3 = "Noto Color Emoji:scale=10;2"
font-4 = "JetBrainsMonoNL NF:size=10;2"

modules-left = xworkspaces
modules-center = date
modules-right = filesystem wifi eth pulseaudio battery tray

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

format-mounted-prefix = " "
format-mounted-prefix-foreground = ${colors.primary}
label-mounted = %free%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

# [module/memory]
# type = internal/memory
# interval = 2
# format-prefix = " "
# format-prefix-foreground = ${colors.primary}
# label = %percentage_used:2%%
# 
# [module/cpu]
# type = internal/cpu
# interval = 2
# format-prefix = " "
# format-prefix-foreground = ${colors.primary}
# label = %percentage:2%%

[module/wifi]
type = internal/network
interface-type = wireless
interval = 1

format-connected = <ramp-signal> <label-connected>
format-disconnected = 
label-connected = %essid%
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.primary}

[module/eth]
type = internal/network
interface-type = wired
interval = 1

format-connected = <label-connected>
format-disconnected = 
label-connected = 🌍 eth0
label-connected-foreground = ${colors.primary}

[module/cava]
type = custom/script
tail = true
exec = $HOME/.config/polybar/cava.sh
format = <label>
format-font = 5
label-foreground = #7A8B8C
label = %output%

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
label-volume-foreground = ${colors.foreground}

label-muted =  muted
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = ${colors.primary}

click-right = pavucontrol

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 99
low-at = 15

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-low = <animation-low> <label-low>

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%
label-low = %percentage%%

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.primary}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.primary}
animation-charging-framerate = 750

animation-low-0 = 
animation-low-1 = 
animation-low-foreground = ${colors.alert}
animation-low-framerate = 200

[module/date]
type = internal/date
interval = 1

date = %a, %b %d
time = %H:%M:%S

format = <label>
label = %date%  %time%
label-foreground = ${colors.primary}

[module/tray]
type = internal/tray
tray-spacing = 0
tray-padding = 2
tray-size = 80%
tray-background = ${colors.background}
tray-foreground = ${colors.foreground}

[settings]
screenchange-reload = true
pseudo-transparency = true
